### ISSUE TITLE
Breaking them up?

### ISSUE THREAD

**Issue by GrimPixel** [hankertrix/Uni-Stuff#1]
I would like to say that it is somehow unique to your own path of study. This is probably a problem of books in general: There are a lot of content, however, each time one has to spend time to find what he/she want.
My approach is, to break everything up to molecules. An example is https://codeberg.org/GrimPixel/SciTech-Index.

**Comment by hankertrix** [comment]
I don’t think you understand the purpose of this repository. This is just the place where I host my own notes and tutorials for the courses I’m taking in university, for the benefit of other people who are also taking the same courses. I’m not trying to make a database or an index of chemical molecules or science definitions.
